application: busridegames
version: 1-1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: (.*)/
  static_files: static\1/main.html
  upload: static/main.html

- url: /
  static_dir: static
  
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico


libraries:
- name: webapp2
  version: "2.5.2"
